### ISSUE TITLE
Shared folders

### ISSUE THREAD

**Issue by Guillaumedesdom** [antoniotejada/obsidian-google-drive#2]
Hello, 
I am using your plugin with 2 accounts and i would like to know if
there is a way to use a shared folder with those two accounts.

Currently, on account n°1, i create a new folder from obsidian google drive plugin. 
I share this folder with account n°2 via Google Drive.
Then, i do the connection process from obsidian google drive plugin.
And it doesn't show me the shared folder when i want to choose the Google Drive folder.

Thanks,

**Comment by antoniotejada** [comment]
With the [default settings](https://github.com/antoniotejada/obsidian-google-drive#default-google-drive-login-settings) the plugin can only open folders created from inside the plugin. When you share the plugin-created folder with another google account, the folder in the other google account was no longer created by the plugin, so you don't see it. 

You will have to use [personalized settings](https://github.com/antoniotejada/obsidian-google-drive#personalized-google-drive-login-settings).

Closing invalid.
